# Generated by Django 3.2.15 on 2022-09-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='writer',
            field=models.IntegerField(),
        ),
    ]
